<?php header('Access-Control-Allow-Origin: *');
  header("Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept");
  require("connect.php");

  // Add the tesseract binary to the system path so that we can call exec
  $path = getenv('PATH');
  putenv("PATH=$path:/usr/local/bin/"); // NOTE: Change this path to wherever the tesseract binary resides on your local system

  $userID = $_GET['userid'];
  $itemName = $_GET['itemName'];

  // Get from parameters the location of the image
  $imagePath = $_GET['imagePath'];
  $outputPath = "tmp/tesseract-ocr-output-".rand();
  $outputArray = array();

  // Call OCR functions and convert to string
  exec("tesseract $imagePath $outputPath");
  $ocrText = nl2br(file_get_contents($outputPath.'.txt'));

  // Split OCR output into lines using newline as delimiter
  $ocrArray = explode("\n", $ocrText);

  // Iterate through the array and use regex matching to idenfity key receipt properties
  foreach ($ocrArray as $line) {
    if (preg_match("/\.\d\d/i", $line)) {

      // Find cost (any string that has a . followed by 2 decimals)
      preg_match("/\.\d\d/i", $line, $cost);

      // Find quantity (some receipts may not list quantity)
      // Quantity is any string of pure numbers in the line
      if (!preg_match("/\s\d+\s/", $line, $quantity)) {
        $quantity[0] = 0;
      }

      // Find name (any string of characters)
      preg_match("/\w+/i", $line, $name);

      // Push into outputArray
      array_push($outputArray, array('name'=>$name[0], 'quantity'=>$quantity[0], 'cost'=>floatval($cost[0])));

    }
  }

  // Encode the outputArray as JSON object
  echo json_encode($outputArray);

  // Clean up files generated by tesseract
  array_map('unlink', glob($outputPath.'.txt'));
?>
